### ISSUE TITLE
Input files  (.inp) 

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [AnargyrosKarakalas/UMAT_3D#1]
Dear Sir,

can we test this umat using an **input file** (.inp)?

Best regards,
Libo

**Comment by AnargyrosKarakalas** [comment]
Dear Libo,

Yes of course. An input file with an example has been uploaded to the repository (please refer to file Coupled_Analysis.inp).

Thank you.

Best regards,
Anargyros

**Comment by asdasdqwdqwfsdf** [comment]
Dear Anargyros,

many thank for your support!

Warm regards,
Libo
